-- Expand work orders so one work order can target trees, fields, or irrigation assets.

begin;

alter table public.work_orders
    add column if not exists title text,
    add column if not exists priority text not null default 'normal',
    add column if not exists due_date date,
    add column if not exists work_notes text,
    add column if not exists target_type text not null default 'tree';

create table if not exists public.work_order_targets (
    work_order_target_id bigint generated by default as identity primary key,
    wo_id integer not null references public.work_orders (wo_id) on delete cascade,
    target_type text not null,
    tree_id text references public.trees (tree_id) on delete cascade,
    field_name text,
    asset_id bigint references public.irrigation_assets (asset_id) on delete cascade,
    notes text,
    created_at timestamptz not null default timezone('utc', now()),
    constraint work_order_targets_exactly_one_target_chk check (
        ((case when tree_id is not null then 1 else 0 end) +
         (case when field_name is not null then 1 else 0 end) +
         (case when asset_id is not null then 1 else 0 end)) = 1
    ),
    constraint work_order_targets_target_type_chk check (
        (target_type = 'tree' and tree_id is not null and field_name is null and asset_id is null) or
        (target_type = 'field' and field_name is not null and tree_id is null and asset_id is null) or
        (target_type = 'irrigation_asset' and asset_id is not null and tree_id is null and field_name is null)
    )
);

create index if not exists work_order_targets_wo_id_idx
    on public.work_order_targets (wo_id);

create index if not exists work_order_targets_tree_id_idx
    on public.work_order_targets (tree_id);

create index if not exists work_order_targets_field_name_idx
    on public.work_order_targets (field_name);

create index if not exists work_order_targets_asset_id_idx
    on public.work_order_targets (asset_id);

insert into public.work_order_targets (wo_id, target_type, tree_id, created_at)
select wo.wo_id, 'tree', wo.tree_id, coalesce(wo.created_at, timezone('utc', now()))
from public.work_orders wo
where wo.tree_id is not null
  and not exists (
      select 1
      from public.work_order_targets wot
      where wot.wo_id = wo.wo_id
  );

commit;
