-- Create irrigation asset register for pumps, headers, laterals, valves, and similar infrastructure.

begin;

create table if not exists public.irrigation_assets (
    asset_id bigint generated by default as identity primary key,
    asset_name text not null,
    asset_type text not null,
    field_name text,
    irrigation_zone text,
    status text not null default 'active',
    latitude numeric,
    longitude numeric,
    notes text,
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists irrigation_assets_asset_type_idx
    on public.irrigation_assets (asset_type);

create index if not exists irrigation_assets_field_name_idx
    on public.irrigation_assets (field_name);

create index if not exists irrigation_assets_irrigation_zone_idx
    on public.irrigation_assets (irrigation_zone);

commit;
